server:
  port: 9191

#logging:
#  level:
#    org.apache.kafka.clients: ERROR

spring:
  application:
    name: user-service
  cache:
    user:
      ttl: 3600

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_service_postgres}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: none  # <--- ВАЖНО: отключить авто-генерацию схемы JPA
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

#  kafka:
#    bootstrap-servers: ${KAFKA_URL:http://localhost:9092}
#    consumer:
#      group:
#        id: user-service
#      advisement-events:
#        topic: advisement-events
#      adviser-application-events:
#        topic: adviser-application-events
#      file-events:
#        topic: file-events
#    producer:
#      user-events:
#        topic: user-events
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog.xml
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_TOKEN_URL:https://auth.dev.advice.it-mentor.space/realms/ITM-Advice}
#
#keycloak:
#  realm: ITM-Advice
#  resource: user-service
#  auth-server-url: ${KEYCLOAK_SERVER_URL:https://auth.dev.advice.it-mentor.space}
#  credentials:
#    secret: ${SECRET:yROFGBQMcPdRG6B8nkHHAXPHSiL4TjpX}
#
#springdoc:
#  swagger-ui:
#    config-url: /${spring.application.name}/v3/api-docs/swagger-config
#    url: /${spring.application.name}/v3/api-docs
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

logging:
  level:
    root: info      # Включает DEBUG для всего приложения
#    com.mycompany: debug  # (опционально) только твои классы